FROM tensorflow/tensorflow:2.2.0
RUN pip3 install --upgrade pip && pip3 install tables \
                    pandas \
                    tensorflow-probability \
                    networkx \
                    tables \
                    matplotlib \
                    jupyter \
                    Levenshtein
