FROM pytorch/pytorch
RUN apt-get update
RUN apt-get install -y  python3-dev \
                        build-essential \
                        automake \
                        bison \
                        libtool \
                        byacc \
                        swig \
                        pkg-config \
                        g++ \
                        gcc \
                        wget \
                        libgtk-3-dev \
                        libcairo2-dev \
                        ghostscript \
                        expat \
                        libpng-dev \
                        zlib1g-dev \
                        libgts-dev \
                        libperl-dev
RUN python -m pip install --upgrade pip setuptools wheel
RUN python -m pip install --upgrade tables \
                    scipy \
                    matplotlib \
                    jupyter \
                    pandas \
                    sympy \
                    nose \
                    networkx \
                    ray \
                    ray[tune] \
                    h5py \
                    tabulate
RUN wget https://www2.graphviz.org/Packages/stable/portable_source/graphviz-2.44.1.tar.gz
RUN tar -xzvf graphviz-2.44.1.tar.gz
RUN cd graphviz-2.44.1 && ./configure && make && make install

RUN python -m pip install --upgrade pygraphviz
RUN python -m pip install --upgrade install pyro-ppl
